# Generated by Django 4.2.5 on 2023-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='default_cover.jpg', upload_to='album_covers/'),
        ),
    ]
