# Generated by Django 4.2.5 on 2023-12-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0002_alter_album_cover'),
        ('app_album_viewer', '0003_alter_album_cover'),
    ]

    operations = [
    ]
