# Generated by Django 4.2.5 on 2023-12-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0004_merge_0002_alter_album_cover_0003_alter_album_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
